# This file can be stored in your repository under .github/workflows/deploy.yml, for example.
name: Deploy
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
env:
    play_while_download_oauth: ${{ secrets.play_while_download_oauth }}
jobs:

    
  deploy:

    
    # Important: must be run from Linux.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'jetbrains'
        
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: print config
        run: ./gradlew :composeApp:printConveyorConfig
      - name: Build with Gradle Wrapper
        run: ./gradlew :composeApp:proguardReleaseJars
      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v19.0
        env:
          OAUTH_TOKEN: ${{ secrets.PLAY_WHILE_DOWNLOAD_OAUTH }}
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGN_KEY }}          
          agree_to_license: 1
          extra_flags: --show-log=error
          cache_key: 'conveyor'
          cache_path: '.conveyor'

